runtime: custom
env: flex

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 5
  disk_size_gb: 40

readiness_check:
  timeout_sec: 100
  check_interval_sec: 150
  app_start_timeout_sec: 1600
