instance_class: B4
runtime: custom
env: flex
manual_scaling:
  instances: 1
resources:
  cpu: 2
  memory_gb: 12
  disk_size_gb: 50

readiness_check:
  timeout_sec: 100
  check_interval_sec: 150
  app_start_timeout_sec: 1600

liveness_check:
  initial_delay_sec: 500
  check_interval_sec: 250
  timeout_sec: 200
  failure_threshold: 4
